# Generated by Django 3.2.11 on 2022-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcode', '0003_alter_flashcard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='defination',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
